---
name: Generate PDF Document
# This workflow generates a PDF document using latexmk and uploads it as an artifact.
# It is triggered on every push to the repository.

on: [push, workflow_dispatch]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate PDF document
        uses: hspaans/latexmk-action@v2.0.1
        with:
          format: pdf
          filename: PrepTable.tex
          options: -shell-escape
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PrepTable-PDF
          path: PrepTable.pdf
