---
name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate PDF document
        uses: hspaans/latexmk-action@v2.0.0
        with:
          format: pdf
          filename: PrepTable.tex
          options: -shell-escape
